// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package repo

import ()

type Credential struct {
	ID       int32
	GuildID  int64
	Name     string
	Url      string
	Username string
	Password string
}

type Guild struct {
	ID           int64
	Name         string
	ServerName   string
	ServerRegion string
	ServerRealm  string
}
